# scripts/examples_publish_all.R
# Build & publish STATIC + SHINYLIVE + QUARTO into docs/examples/*/*
# Works locally and in CI; avoids double-bracket vector indexing on lists.

if (file.exists("renv/activate.R")) source("renv/activate.R")

`%||%` <- function(a, b) if (is.null(a) || length(a) == 0) b else a
safe_len <- function(x) if (is.null(x)) 0L else length(x)

copy_dir_contents <- function(from_dir, dest_dir) {
  stopifnot(dir.exists(from_dir))
  if (dir.exists(dest_dir)) unlink(dest_dir, recursive = TRUE, force = TRUE)
  dir.create(dest_dir, recursive = TRUE, showWarnings = FALSE)
  files <- list.files(from_dir, full.names = TRUE, all.files = TRUE, no.. = TRUE)
  ok <- file.copy(files, dest_dir, recursive = TRUE, overwrite = TRUE)
  if (!all(ok)) stop("Failed to copy some files from ", from_dir, " to ", dest_dir)
  invisible(dest_dir)
}

render_quarto_site <- function(quarto_dir) {
  if (!nzchar(quarto::quarto_path())) {
    message("Quarto CLI not available; skipping render for: ", quarto_dir)
    return(invisible(NULL))
  }
  quarto::quarto_render(quarto_dir, quiet = TRUE)
  file.path(quarto_dir, "_site")
}

build_four <- function(spec_path, name) {
  base <- file.path(getwd(), "examples_out", name)
  dir.create(base, recursive = TRUE, showWarnings = FALSE)
  
  static_dir    <- zashboard::build_static   (spec_path, out_dir = file.path(base, "static"),    overwrite = TRUE)
  shinylive_dir <- zashboard::build_shinylive(spec_path, out_dir = file.path(base, "shinylive"), overwrite = TRUE)
  quarto_dir    <- zashboard::build_quarto   (spec_path, out_dir = file.path(base, "quarto"),    overwrite = TRUE, render = FALSE)
  shiny_app     <- zashboard::build_shiny    (spec_path)
  
  list(static_dir = static_dir,
       shinylive_dir = shinylive_dir,
       quarto_dir = quarto_dir,
       shiny_app = shiny_app)
}

publish_one <- function(b, name) {
  static_dest    <- file.path("docs", "examples", name, "static")
  shinylive_dest <- file.path("docs", "examples", name, "shinylive")
  quarto_dest    <- file.path("docs", "examples", name, "quarto")
  
  copy_dir_contents(b$static_dir, static_dest)
  
  if (!is.null(b$shinylive_dir) && dir.exists(b$shinylive_dir)) {
    copy_dir_contents(b$shinylive_dir, shinylive_dest)
  } else {
    message("Shinylive not built for ", name, " (skipping).")
  }
  
  site <- render_quarto_site(b$quarto_dir)
  if (!is.null(site) && dir.exists(site)) {
    copy_dir_contents(site, quarto_dest)
  }
  
  invisible(list(static = static_dest, shinylive = shinylive_dest, quarto = quarto_dest))
}

write_examples_index <- function() {
  # relative links and explicit index.html to avoid directory listing & 404s
  dir.create(file.path("docs","examples"), recursive = TRUE, showWarnings = FALSE)
  mk <- function(name, title) sprintf(
    "<li>%s — <a href='./%s/static/index.html'>static</a> · <a href='./%s/shinylive/index.html'>shinylive</a> · <a href='./%s/quarto/index.html'>quarto</a></li>",
    title, name, name, name
  )
  html <- c(
    "<!doctype html><meta charset='utf-8'>",
    "<body style='font-family:system-ui,Segoe UI,Arial;margin:24px'>",
    "<h1>Zashboard demos</h1>",
    "<p>Each demo is published in three flavors: static HTML, Shinylive (client-side Shiny), and Quarto.</p>",
    "<ul>",
    mk("iris","Iris"),
    mk("airquality","Airquality"),
    mk("toothgrowth","ToothGrowth"),
    mk("co2","CO2"),
    "</ul>",
    "<p>Generated by <code>scripts/examples_publish_all.R</code></p>",
    "</body>"
  )
  writeLines(html, file.path("docs","examples","index.html"))
  # prevent GH Pages from trying to process this site with Jekyll
  writeLines("", file.path("docs", ".nojekyll"))
}

# ---- Build & publish all four ------------------------------------------------
b_iris <- build_four("inst/examples/iris/iris.yml",               "iris")
b_air  <- build_four("inst/examples/airquality/airquality.yml",   "airquality")
b_tg   <- build_four("inst/examples/toothgrowth/toothgrowth.yml", "toothgrowth")
b_co2  <- build_four("inst/examples/co2/co2.yml",                 "co2")

publish_one(b_iris, "iris")
publish_one(b_air,  "airquality")
publish_one(b_tg,   "toothgrowth")
publish_one(b_co2,  "co2")

write_examples_index()

message("All demos published under docs/examples/.")
