# scripts/examples_publish_static.R
# Publish the four example *static* builds into docs/examples/*/static

if (file.exists("renv/activate.R")) source("renv/activate.R")

# Helper: build all four targets for a spec (you already used this)
build_four <- function(spec_path, name) {
  base <- file.path(getwd(), "examples_out", name)
  dir.create(base, recursive = TRUE, showWarnings = FALSE)
  
  static_dir    <- zashboard::build_static   (spec_path, out_dir = file.path(base, "static"),    overwrite = TRUE)
  shinylive_dir <- zashboard::build_shinylive(spec_path, out_dir = file.path(base, "shinylive"), overwrite = TRUE)
  quarto_dir    <- zashboard::build_quarto   (spec_path, out_dir = file.path(base, "quarto"),    overwrite = TRUE, render = FALSE)
  shiny_app     <- zashboard::build_shiny    (spec_path)
  
  list(static_dir = static_dir,
       shinylive_dir = shinylive_dir,
       quarto_dir = quarto_dir,
       shiny_app = shiny_app)
}

# Helper: copy the *contents* of <from_dir> into <dest_dir>
copy_dir_contents <- function(from_dir, dest_dir) {
  if (!dir.exists(from_dir)) stop("Source directory does not exist: ", from_dir)
  if (dir.exists(dest_dir)) unlink(dest_dir, recursive = TRUE, force = TRUE)
  dir.create(dest_dir, recursive = TRUE, showWarnings = FALSE)
  
  files <- list.files(from_dir, full.names = TRUE, all.files = TRUE, no.. = TRUE)
  ok <- file.copy(from = files, to = dest_dir, overwrite = TRUE, recursive = TRUE)
  if (!all(ok)) {
    bad <- files[!ok]
    stop("Failed to copy some files to ", dest_dir, ":\n", paste(" -", bad, collapse = "\n"))
  }
  invisible(dest_dir)
}

# Build the 4 examples (uses your inst/examples/*/*.yml)
b_iris <- build_four("inst/examples/iris/iris.yml",               "iris")
b_air  <- build_four("inst/examples/airquality/airquality.yml",   "airquality")
b_tg   <- build_four("inst/examples/toothgrowth/toothgrowth.yml", "toothgrowth")
b_co2  <- build_four("inst/examples/co2/co2.yml",                 "co2")

# Publish static outputs under docs/examples/*/static
publish_one <- function(b, name) {
  dest <- file.path("docs", "examples", name, "static")
  copy_dir_contents(b$static_dir, dest)
  message("Published static: ", normalizePath(dest, winslash = "/"))
}

publish_one(b_iris, "iris")
publish_one(b_air,  "airquality")
publish_one(b_tg,   "toothgrowth")
publish_one(b_co2,  "co2")

# Simple index page linking to each static demo
index_html <- c(
  "<!doctype html>",
  "<meta charset='utf-8'>",
  "<title>Zashboard examples</title>",
  "<body style='font-family:system-ui,Segoe UI,Arial;margin:24px'>",
  "<h1>Zashboard examples</h1>",
  "<ul>",
  "<li><a href='iris/static/index.html'>Iris (static)</a></li>",
  "<li><a href='airquality/static/index.html'>Airquality (static)</a></li>",
  "<li><a href='toothgrowth/static/index.html'>ToothGrowth (static)</a></li>",
  "<li><a href='co2/static/index.html'>CO2 (static)</a></li>",
  "</ul>",
  "<p>Generated by <code>scripts/examples_publish_static.R</code></p>",
  "</body>"
)
dir.create(file.path("docs","examples"), recursive = TRUE, showWarnings = FALSE)
writeLines(index_html, file.path("docs", "examples", "index.html"))
message("Wrote examples index: ", normalizePath(file.path("docs","examples","index.html"), winslash = "/"))
