#' Build a minimal Shinylive bundle
#'
#' Writes `index.html` and `app.json` suitable for browser-executed Shiny
#' (Shinylive). This is a minimal stub used for tests and local demos.
#'
#' @param spec Path to a YAML spec file, or a list already read in.
#' @param out_dir Directory to write the bundle into. Defaults to
#'   `file.path(tempdir(), "zashboard-shinylive")`.
#' @param overwrite Logical; if `FALSE` (default) and `out_dir` exists, error.
#' @param title Optional page title override; defaults to `spec$title` or "Zashboard (Shinylive)".
#' @param ... Not used currently; reserved for future extensions.
#' @return Invisibly, the normalized output directory path.
#' @export
#' @importFrom jsonlite write_json

build_shinylive <- function(spec = NULL,
                            out_dir = file.path(tempdir(), "zashboard-shinylive"),
                            overwrite = FALSE,
                            title = NULL,
                            ...) {
  `%||%` <- function(a, b) if (is.null(a) || length(a) == 0) b else a
  
  sp <- zashboard_read_validate(spec)
  page_title <- title %||% sp$title %||% "Zashboard (Shinylive)"
  
  out_dir <- normalizePath(out_dir, winslash = "/", mustWork = FALSE)
  if (dir.exists(out_dir) && !overwrite) {
    stop("Output directory already exists: ", out_dir,
         " (set overwrite = TRUE to replace).", call. = FALSE)
  }
  if (dir.exists(out_dir) && overwrite) unlink(out_dir, recursive = TRUE, force = TRUE)
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  
  # Minimal manifest with top-level `charts`
  manifest <- list(
    title    = page_title,
    datasets = sp$datasets %||% list(),
    charts   = sp$charts   %||% list()
  )
  
  # Write compact JSON where "charts":[ has no space (test expectation)
  title_json    <- jsonlite::toJSON(manifest$title,    auto_unbox = TRUE)
  datasets_json <- jsonlite::toJSON(manifest$datasets, auto_unbox = TRUE)
  charts_json   <- jsonlite::toJSON(manifest$charts,   auto_unbox = TRUE)
  
  json_txt <- sprintf('{"title":%s,"datasets":%s,"charts":%s}',
                      title_json, datasets_json, charts_json)
  
  writeLines(json_txt, file.path(out_dir, "app.json"))
  
  
  # Minimal index.html
  esc <- function(x) {
    x <- as.character(x %||% "")
    x <- gsub("&","&amp;",x,fixed=TRUE)
    x <- gsub("<","&lt;" ,x,fixed=TRUE)
    x <- gsub(">","&gt;" ,x,fixed=TRUE)
    x
  }
  lines <- c(
    "<!doctype html>",
    "<html><head>",
    sprintf("<title>%s (Shinylive)</title>", esc(page_title)),
    "</head><body>",
    sprintf("<h1>%s (Shinylive)</h1>", esc(page_title)),
    sprintf("<p><strong>Datasets:</strong> %d &nbsp; <strong>Charts:</strong> %d</p>",
            length(sp$datasets %||% list()), length(sp$charts %||% list())),
    "<p><small>Generated by <code>zashboard::build_shinylive()</code></small></p>",
    "</body></html>"
  )
  writeLines(lines, file.path(out_dir, "index.html"))
  
  invisible(out_dir)
}
