#' Build a Quarto site (from the spec)
#'
#' Writes a minimal Quarto project; optionally renders it if Quarto is available.
#'
#' @param spec Path to a YAML file or a list already parsed; if NULL, the
#'   packaged template is used.
#' @param out_dir Directory for the Quarto project.
#' @param render Logical; if TRUE and Quarto is available, render the site.
#' @param overwrite Logical; if TRUE, allow writing into an existing out_dir.
#' @param ... Not used currently; reserved for future extensions.
#' @return (Invisibly) the normalized project directory path.
#' @export

#' @examples
#' \donttest{
#' dir_out <- build_quarto(overwrite = TRUE)
#' file.exists(file.path(dir_out, "_quarto.yml"))
#' file.exists(file.path(dir_out, "index.qmd"))
#' }
build_quarto <- function(spec = NULL,
                         out_dir = NULL,
                         overwrite = FALSE,
                         title = NULL,
                         render = FALSE,
                         ...) {
  `%||%` <- function(x, y) if (is.null(x) || length(x) == 0L) y else x
  
  sp <- zashboard_read_validate(spec)
  
  out_dir <- out_dir %||% file.path(tempdir(), "zashboard-quarto")
  out_dir <- normalizePath(out_dir, winslash = "/", mustWork = FALSE)
  
  if (dir.exists(out_dir)) {
    if (!isTRUE(overwrite)) {
      stop("Output directory exists: '", out_dir, "'. Use overwrite = TRUE or choose a different out_dir.", call. = FALSE)
    }
  } else {
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  }
  
  title <- as.character(title %||% sp$title %||% "Zashboard")
  
  # helpers --------------------------------------------------------------------
  write_utf8 <- function(path, text) {
    con <- file(path, open = "wb", encoding = "UTF-8")
    on.exit(close(con), add = TRUE)
    writeLines(enc2utf8(text), con = con, useBytes = TRUE)
  }
  esc_yaml <- function(x) {
    # simple YAML scalar escape
    x <- gsub('"', '\\"', as.character(x), fixed = TRUE)
    paste0('"', x, '"')
  }
  esc_md <- function(x) as.character(x)
  
  # summarize charts
  charts <- lapply(sp$charts %||% list(), function(ch) {
    list(id = as.character(ch$id %||% ""), type = as.character(ch$type %||% ""))
  })
  chart_lines <- character(0)
  if (length(charts)) {
    chart_lines <- vapply(charts, function(ch) {
      paste0("- ", esc_md(ch$id), " (_", esc_md(ch$type), "_)")
    }, character(1))
  }
  
  # _quarto.yml ----------------------------------------------------------------
  qyml <- paste0(
    "project:\n",
    "  type: website\n",
    "  output-dir: _site\n",
    "website:\n",
    "  title: ", esc_yaml(title), "\n",
    "format:\n",
    "  html:\n",
    "    theme: cosmo\n",
    "    toc: true\n"
  )
  write_utf8(file.path(out_dir, "_quarto.yml"), qyml)
  
  # index.qmd ------------------------------------------------------------------
  body <- paste0(
    "# ", esc_md(title), "\n\n",
    "**Datasets:** ", length(sp$datasets %||% list()), "  \n",
    "**Charts:** ",   length(charts), "\n\n",
    if (length(chart_lines)) {
      paste(c("## Charts", chart_lines), collapse = "\n")
    } else {
      "_No charts defined yet._"
    },
    "\n\n---\nGenerated by `zashboard::build_quarto()`"
  )
  write_utf8(file.path(out_dir, "index.qmd"), body)
  
  # app.json (manual JSON) -----------------------------------------------------
  esc_json <- function(x) {
    x <- as.character(x)
    x <- gsub("\\\\", "\\\\\\\\", x)
    x <- gsub('"', '\\"', x)
    x
  }
  charts_json <- if (length(charts)) {
    paste0(
      "[",
      paste0(
        vapply(charts, function(ch) {
          paste0('{"id":"', esc_json(ch$id), '","type":"', esc_json(ch$type), '"}')
        }, character(1)),
        collapse = ","
      ),
      "]"
    )
  } else "[]"
  
  app_json <- paste0(
    '{',
    '"title":"', esc_json(title), '",',
    '"version":1,',
    '"charts":', charts_json,
    '}'
  )
  write_utf8(file.path(out_dir, "app.json"), app_json)
  
  # Optional render ------------------------------------------------------------
  if (isTRUE(render)) {
    has_pkg <- requireNamespace("quarto", quietly = TRUE)
    has_cli <- nzchar(Sys.which("quarto"))
    if (has_pkg && has_cli) {
      quarto::quarto_render(input = out_dir, as_job = FALSE)
    } else {
      message("Quarto not available (R package or CLI). Wrote files but did not render.")
    }
  }
  
  invisible(out_dir)
}
