#' Build static HTML output
#'
#' Reads and validates a Zashboard spec, then writes a minimal `index.html`
#' to the output directory and copies package assets (CSS/JS) if present.
#'
#' @inheritParams zashboard_read_spec
#' @param out_dir Directory to write the site into. Defaults to
#'   `file.path(tempdir(), "zashboard-static")`.
#' @param overwrite Logical; if `FALSE` (default) and `out_dir` exists, error.
#' @param title Optional page title override; defaults to `spec$title` or "Zashboard".
#' @return (Invisibly) the normalized output directory path.
#' @export
build_static <- function(spec = NULL, out_dir = NULL, overwrite = FALSE, title = NULL, ...) {
  `%||%` <- function(x, y) if (is.null(x) || length(x) == 0L) y else x
  
  sp <- zashboard_read_validate(spec)
  
  out_dir <- out_dir %||% file.path(tempdir(), "zashboard-static")
  out_dir <- normalizePath(out_dir, winslash = "/", mustWork = FALSE)
  
  if (dir.exists(out_dir)) {
    if (!isTRUE(overwrite)) {
      stop("Output directory exists: '", out_dir, "'. Use overwrite = TRUE or choose a different out_dir.", call. = FALSE)
    }
  } else {
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  }
  
  title <- as.character(title %||% sp$title %||% "Zashboard")
  
  # ---- copy assets from the installed package (or dev source fallback) ----
  assets_src <- system.file("www", "assets", package = "zashboard")
  if (!nzchar(assets_src)) {
    # dev fallback when not installed yet
    maybe <- file.path(getwd(), "inst", "www", "assets")
    if (dir.exists(maybe)) assets_src <- maybe
  }
  assets_rel  <- "assets"
  assets_dest <- file.path(out_dir, assets_rel)
  copied <- FALSE
  if (nzchar(assets_src) && dir.exists(assets_src)) {
    dir.create(assets_dest, recursive = TRUE, showWarnings = FALSE)
    files <- list.files(assets_src, full.names = TRUE, all.files = FALSE, no.. = TRUE)
    if (length(files)) {
      ok <- file.copy(from = files, to = assets_dest, overwrite = TRUE, recursive = TRUE)
      copied <- any(ok)
    }
  }
  
  # Gather a tiny bit of data from the spec
  n_ds  <- length(sp$datasets %||% list())
  n_ch  <- length(sp$charts   %||% list())
  items <- character(0)
  if (n_ch > 0) {
    items <- vapply(sp$charts, function(ch) {
      id   <- as.character(ch$id   %||% "")
      type <- as.character(ch$type %||% "")
      trimws(sprintf("%s (%s)", id, type))
    }, character(1))
  }
  
  esc <- function(x) {
    x <- as.character(x)
    x <- gsub("&", "&amp;", x, fixed = TRUE)
    x <- gsub("<", "&lt;",  x, fixed = TRUE)
    x <- gsub(">", "&gt;",  x, fixed = TRUE)
    x
  }
  
  # Link assets if they exist
  css_rel <- file.path(assets_rel, "zashboard.css")
  js_rel  <- file.path(assets_rel, "zashboard.js")
  has_css <- file.exists(file.path(out_dir, css_rel))
  has_js  <- file.exists(file.path(out_dir, js_rel))
  assets_head <- paste0(
    if (has_css) paste0("<link rel='stylesheet' href='", css_rel, "'/>") else "",
    if (has_js)  paste0("<script src='", js_rel, "' defer></script>") else ""
  )
  
  html_min <- paste0(
    "<!DOCTYPE html>",
    "<html lang='en'><head><meta charset='utf-8'/>",
    "<meta name='viewport' content='width=device-width,initial-scale=1'/>",
    "<title>", esc(title), "</title>",
    if (nchar(assets_head)) assets_head else
      "<style>body{font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:2rem;max-width:800px}h1{margin-top:0}ul{line-height:1.6}</style>",
    "</head><body>",
    "<h1>", esc(title), "</h1>",
    "<p><strong>Datasets:</strong> ", n_ds, " &nbsp; ",
    "<strong>Charts:</strong> ", n_ch, "</p>",
    if (length(items)) {
      paste0("<ul>", paste0("<li>", esc(items), "</li>", collapse = ""), "</ul>")
    } else {
      "<p>No charts defined yet.</p>"
    },
    "<div class='footer'>Generated by zashboard::build_static()</div>",
    "</body></html>"
  )
  
  # Write index.html (UTF-8)
  index <- file.path(out_dir, "index.html")
  con <- file(index, open = "wb", encoding = "UTF-8")
  on.exit(close(con), add = TRUE)
  writeLines(enc2utf8(html_min), con = con, useBytes = TRUE)
  
  invisible(out_dir)
}
